/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import com.sun.corba.se.spi.orbutil.fsm.Input;
import java.io.*;
import java.net.Socket;
import java.net.UnknownHostException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author DIVYA
 */
public class Clientbox extends javax.swing.JFrame {

    /**
     * Creates new form Clientbox
     */
    String ip;
   // int portnumber;
    String name;
    private Socket c;
    private PrintWriter pw;
    private BufferedReader brc;
    //InputStreamReader isr;
    MultiClient mc;
    GetChatMessage gt;

    
    public Clientbox() {
        initComponents();
        setResizable(false);
        setTitle("CHAT BOX");
        setLocation(100, 300);
        tport.requestFocus();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }
    
    class MultiClient
    {
     public MultiClient(String ip, int port)
     {
         try{
             name = tname.getText();
             c = new Socket(ip, port);
             fetchAndCreateStreams();
             
         }
         catch(UnknownHostException e)
         {
             ta1.append("The host is unreachable.");
             JOptionPane.showMessageDialog(null, e.getMessage());
         }
         catch(Exception e)
         {
             JOptionPane.showMessageDialog(null, e.getMessage());
         }
     }
     private void fetchAndCreateStreams()
     {
         try
         { 
             brc = new BufferedReader(new InputStreamReader(c.getInputStream()));
             pw = new PrintWriter(c.getOutputStream(),true);
            
         }
         catch(Exception e)
         {
             JOptionPane.showMessageDialog(null, e.getMessage());
         }
     }
     
     public void work()
     {
         gt.start();
     }
    }  
   class GetChatMessage extends Thread 
   {
       Socket c;
       BufferedReader brc;

        public GetChatMessage(Socket c) {
            this.c = c;
        }

        public void run() {
            try {
                String msg = "";

                brc = new BufferedReader(new InputStreamReader(c.getInputStream()));
                do {
                    try {
                        msg = brc.readLine();
                    } catch (Exception e) {
                    }
                   ta1.append(msg + "\n");
                } while (true);
            } catch (Exception e) {
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tport = new javax.swing.JTextField();
        bconnect = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tip = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta1 = new javax.swing.JTextArea();
        bsend = new javax.swing.JButton();
        tf4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tname = new javax.swing.JTextField();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CHAT BOX");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Port Number");
        jLabel2.setFocusable(false);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tport.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        bconnect.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        bconnect.setText("Connect");
        bconnect.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bconnectActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("User Name");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tip.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        ta1.setColumns(20);
        ta1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        ta1.setRows(5);
        jScrollPane1.setViewportView(ta1);

        bsend.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        bsend.setText("Send");
        bsend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsendActionPerformed(evt);
            }
        });

        tf4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("IP Address");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tname.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(tf4, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(bsend))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tip, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tport, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tname, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bconnect)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(bconnect))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(bsend))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(tf4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bconnectActionPerformed
        // TODO add your handling code here:
        if (tname.getText().equalsIgnoreCase("") || tport.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "Invalid User name or Port Number");

        } else {
           tf4.setEnabled(true);
           bsend.setEnabled(true);
           String port = tport.getText();
           int port1 = Integer.parseInt(port);
           ip = tip.getText();
           mc = new MultiClient(ip,port1);
           gt = new GetChatMessage(c);
          
           JOptionPane.showMessageDialog(null, "Start your chat");
           ta1.setText("Enjoy Your Chat :-) :-) \n");
           ta1.append("Enter your user name as the first message to LOGIN \n");
           gt.start();
           
           tname.setEnabled(false);
           bconnect.setEnabled(false);
    }//GEN-LAST:event_bconnectActionPerformed
    }
    private void bsendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsendActionPerformed
        // TODO add your handling code here:
        String gmsg;
        gmsg = tf4.getText();
      //gmsg = name + ":-" + tf4.getText() + "\n";
       //try
       // {
        pw.println(gmsg);
        tf4.setText("");
        //}
      /*  catch(NullPointerException e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }*/
    }//GEN-LAST:event_bsendActionPerformed

    /**
     * @param args the command line arguments
     */
 
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bconnect;
    private javax.swing.JButton bsend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea ta1;
    private javax.swing.JTextField tf4;
    private javax.swing.JTextField tip;
    private javax.swing.JTextField tname;
    private javax.swing.JTextField tport;
    // End of variables declaration//GEN-END:variables
}
